# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-06 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorganization',
            name='location',
            field=models.CharField(max_length=150, verbose_name='机构地址'),
        ),
    ]
