# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-07 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180806_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorganization',
            name='course_nums',
            field=models.IntegerField(default=0, verbose_name='课程数'),
        ),
        migrations.AddField(
            model_name='courseorganization',
            name='students',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
    ]
