# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-27 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180820_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorganization',
            name='tag',
            field=models.CharField(default='全国知名', max_length=10, verbose_name='机构标签'),
        ),
    ]
