# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('chuji', '初级'), ('zhongji', '中级'), ('gaoji', '高级')], max_length=7, verbose_name='难度'),
        ),
    ]
