# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-08 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180808_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('chuji', '初级'), ('zhongji', '中级'), ('gaoji', '高级')], max_length=10),
        ),
    ]
