# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-20 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='url',
        ),
    ]
